name: Automated tests

on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose target
          required: true
          default:
          type: choice
          options:
            - smoke
            - regression

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: Smoke test
              if: "github.event.inputs.deployment_target == 'smoke'"
              run: pytest -v -m smoke
            - name: Regression test
              if: "github.event.inputs.deployment_target == 'regression'"
              run: pytest -v -m regression   
